# This role configures Apache for the application
---

- name: deploy demoapp.conf file
  template:
    src: demoapp.conf
    dest: /etc/httpd/conf.d/demoapp.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart httpd

- name: include db variables
  include_vars:
    file: group_vars/dbservers

- name: config demoapp
  lineinfile:
    dest: /var/www/html/config.php
    regexp: '{{ item.from }}'
    line: '{{ item.to }}'
    state: present
  with_items:
    - { from: '^\$username', to: '$username   = "{{ dbuser }}";' }
    - { from: '^\$password', to: '$password   = "{{ upassword }}";' }
    - { from: '^\$dbname',   to: '$dbname     = "{{ dbname }}";' }
