# This role contains common plays that will run on all nodes.
---

- name: Install EPEL
  yum:
     name: epel-release
     state: present
  tags: epel

- name: Install chrony
  yum:
    name: chrony
    state: present
  tags: chrony

- name: Deploy chrony.conf file
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  tags: chrony
  notify: restart chrony

- name: Start the chrony service
  service:
    name: chronyd
    state: started
    enabled: true
  tags: chrony 

- name: test to see if selinux is running
  command: getenforce
  register: sestatus
  changed_when: false
